### ISSUE TITLE
Error in QA

### ISSUE THREAD

**Issue by whoafridi** [sanigam/BERT_QA_Medium#1]
Gives an error in your code that I've tried in recent days! can you give me solution for this ???
Screenshot & error status available below .::
```py
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-fa96e99fcb8e> in <module>()
     57 
     58 #Testing function
---> 59 bert_answering_machine ("Which state john's friend lives", 'My name is John. I live in San Jose, California. Rob is my friend. He lives in Seattle, Washington')

<ipython-input-4-fa96e99fcb8e> in bert_answering_machine(question, passage, max_len)
     29 
     30     #Converting scores tensors to numpy arrays so that we can use numpy functions
---> 31     start_token_scores = start_token_scores.detach().numpy().flatten()
     32     end_token_scores = end_token_scores.detach().numpy().flatten()
     33 

AttributeError: 'str' object has no attribute 'detach'
```

![image](https://user-images.githubusercontent.com/35966401/102751203-72c89900-4391-11eb-9a74-d555055a6a06.png)

**Comment by Degananda264** [comment]
convert the start_token_scores,end_token_scores line of code into two lines as per below
# getting start and end scores for answer. Converting input arrays to torch tensors before passing to the model
    start_token_scores = model(torch.tensor([input_ids]), token_type_ids=torch.tensor([segment_ids]) )[0]
    end_token_scores = model(torch.tensor([input_ids]), token_type_ids=torch.tensor([segment_ids]) )[1]
and run the same will give expected output

**Comment by whoafridi** [comment]
Yes it works. Is the error for the new transformers updated package?

**Comment by Degananda264** [comment]
yeah might be

**Comment by whoafridi** [comment]
Thanks for response .
